name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

jobs:
  push_to_registry:
    # Use CI environment secrets
    environment: "Continuous Integration"
    
    name: Push massif-visualizer image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: tkreind
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push massif-visualizer
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=tkreind/massif-visualizer-novnc:latest
          cache-to: type=inline
          tags: tkreind/massif-visualizer-novnc:latest
          build-args: |
            PACKAGE_NAME=massif-visualizer
            EXECUTABLE_NAME=massif-visualizer
      -
        name: Build and push gimp
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=tkreind/gimp-novnc:latest
          cache-to: type=inline
          tags: tkreind/gimp-novnc:latest
          build-args: |
            PACKAGE_NAME=gimp
